name: Issue - Bug Report
description: New bug report

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: core-ver
    attributes:
      label: Version Pi-hole (Core)
      options:
        - v5.9.1
        - v5.9
        - v5.8.1
        - v5.8
        - v5.7
        - v5.6
        - Other
  - type: dropdown
    id: web-ver
    attributes:
      label: Version Web (AdminLTE)
      options:
        - v5.11.1
        - v5.11
        - v5.10.1
        - v5.10
        - v5.9
        - v5.9
        - Other
  - type: dropdown
    id: ftl-ver
    attributes:
      label: Version FTL
      options:
        - v5.14.1
        - v5.14
        - v5.13
        - v5.12.1
        - v5.12
        - v5.11
        - Other
    validations:
      required: true
  - type: checkboxes
    id: has-docker
    attributes:
      label: Docker
      options:
        - label: I'm using a docker installation
          required: true
  - type: input
    id: docker-ver
    attributes:
      label: Docker Version
      placeholder: "Docker vesion if used (optional)"
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Details
      description: Describe what you see. Try to detail your steps to reproduce the bug.
      placeholder: Bug Description
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
