name: Issue - Bug Report
description: New bug report

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: core-ver
    attributes:
      label: Pi-hole Version (Core)
    validations:
      required: true
  - type: input
    id: web-ver
    attributes:
      label: Web Version (AdminLTE)
    validations:
      required: true
  - type: input
    id: ftl-ver
    attributes:
      label: FTL Version
    validations:
      required: true
  - type: checkboxes
    id: has-docker
    attributes:
      label: Docker
      options:
        - label: I'm using a docker installation
          required: true
  - type: input
    id: docker-ver
    attributes:
      label: Docker Version
      placeholder: "Docker vesion if used (optional)"
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Details
      description: Describe what you see. Try to detail your steps to reproduce the bug.
      placeholder: Bug Description
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
